FROM --platform=linux/amd64 python:3.11-slim

# Install required system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    clang \
    git \
    pkg-config \
    zlib1g-dev \
    libcap-dev \
    libseccomp-dev \
    libprotobuf-dev \
    protobuf-compiler \
    flex \
    bison \
    libnl-3-dev \
    libnl-genl-3-dev \
    libnl-route-3-dev \
    ca-certificates \
    curl \
    unzip \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Clone and build nsjail
RUN git clone https://github.com/google/nsjail.git /opt/nsjail && \
    cd /opt/nsjail && \
    git checkout 90171fa06d3cb29e0122a37bb884fefabf2f82a && \
    make && \
    cp nsjail /usr/local/bin/nsjail

# Set workdir and copy app
WORKDIR /app
COPY ./app /app
COPY ./nsjail/nsjail.cfg /app/nsjail.cfg
COPY ./scripts /scripts
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]
